# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-09 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.CharField(max_length=256)),
                ('nombre', models.CharField(max_length=256)),
                ('negocio', models.CharField(max_length=256)),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField()),
                ('texto', models.TextField(max_length=2000)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='estaticos/posts_imagenes/')),
            ],
            options={
                'ordering': ('fecha_publicacion',),
            },
        ),
    ]
