# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-26 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muro', '0003_auto_20181108_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fecha_vencimiento',
            field=models.DateTimeField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, default=True, null=True, upload_to='estaticos/posts_imagenes/'),
        ),
    ]
